/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_supermarket;

import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abdo Rehab
 */
public class main_su extends javax.swing.JFrame {

    /**
     * Creates new form main_su
     */
    public main_su() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        id_tex = new javax.swing.JTextField();
        pri_tex = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pro_na_tex = new javax.swing.JTextField();
        quan_tex = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        combe_size = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        add_but1 = new javax.swing.JButton();
        delete_but = new javax.swing.JButton();
        update_but = new javax.swing.JButton();
        total_but = new javax.swing.JButton();
        cost_tex = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Id");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(52, 28, 55, 16);

        id_tex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_texActionPerformed(evt);
            }
        });
        jPanel1.add(id_tex);
        id_tex.setBounds(50, 60, 55, 20);
        jPanel1.add(pri_tex);
        pri_tex.setBounds(590, 60, 63, 20);

        jLabel3.setFont(new java.awt.Font("Lucida Handwriting", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Product_Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(171, 26, 115, 20);

        jLabel4.setFont(new java.awt.Font("Lucida Handwriting", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Quantity");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(334, 26, 74, 20);
        jPanel1.add(pro_na_tex);
        pro_na_tex.setBounds(170, 60, 115, 20);
        jPanel1.add(quan_tex);
        quan_tex.setBounds(340, 60, 74, 20);

        jLabel5.setFont(new java.awt.Font("Lucida Handwriting", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Size");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(472, 28, 80, 16);

        combe_size.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Null", "Large", "Middle", "Small" }));
        jPanel1.add(combe_size);
        combe_size.setBounds(470, 60, 80, 20);

        jScrollPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseClicked(evt);
            }
        });

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "product_nam", "quantity", "size", "price"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table1);

        jScrollPane2.setViewportView(jScrollPane3);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(40, 120, 460, 170);

        add_but1.setBackground(new java.awt.Color(255, 255, 0));
        add_but1.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        add_but1.setForeground(new java.awt.Color(0, 102, 255));
        add_but1.setText("Add");
        add_but1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_but1ActionPerformed(evt);
            }
        });
        jPanel1.add(add_but1);
        add_but1.setBounds(520, 130, 107, 31);

        delete_but.setBackground(new java.awt.Color(255, 255, 0));
        delete_but.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        delete_but.setForeground(new java.awt.Color(0, 102, 255));
        delete_but.setText("Delete");
        delete_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_butActionPerformed(evt);
            }
        });
        jPanel1.add(delete_but);
        delete_but.setBounds(600, 200, 100, 30);

        update_but.setBackground(new java.awt.Color(255, 255, 51));
        update_but.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        update_but.setForeground(new java.awt.Color(0, 102, 255));
        update_but.setText("Update");
        update_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_butActionPerformed(evt);
            }
        });
        jPanel1.add(update_but);
        update_but.setBounds(520, 260, 100, 30);

        total_but.setBackground(new java.awt.Color(255, 255, 0));
        total_but.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        total_but.setForeground(new java.awt.Color(0, 102, 255));
        total_but.setText("Total");
        total_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_butActionPerformed(evt);
            }
        });
        jPanel1.add(total_but);
        total_but.setBounds(30, 310, 107, 31);

        cost_tex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cost_texActionPerformed(evt);
            }
        });
        jPanel1.add(cost_tex);
        cost_tex.setBounds(160, 310, 100, 30);

        jLabel7.setFont(new java.awt.Font("Lucida Handwriting", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Price");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(589, 26, 63, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abdo Rehab\\Desktop\\bd609f6c8dbf1f2c6b42de08cd8caa0e3ffc12e2.jpg")); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 710, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_but1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_but1ActionPerformed

        DefaultTableModel model = (DefaultTableModel) table1.getModel();  
         Vector v=new Vector();//id
         Vector w=new Vector();//name
        for(int i=0;i<table1.getRowCount();i++){
            v.add(table1.getValueAt(i, 0));
            w.add(table1.getValueAt(i, 1));
        }
        if(v.contains(id_tex.getText())){
            JOptionPane.showMessageDialog(null, "id founded please Change id ");
        }
        
        else if(w.contains(pro_na_tex.getText())){
            JOptionPane.showMessageDialog(null, "name founded you are Register ");
        }
        else{
            double z;
            
            String quant=quan_tex.getText();
            double quan=Double.parseDouble(quant);
             String price=pri_tex.getText();
            double pric=Double.parseDouble(price);
            z=quan*pric;//ضرب العدد ف السعر
       
        
        String total = Double.toString(z);//ضرب العدد ف السعر 
        pri_tex.setText(total);
             model.addRow(new Object[]{id_tex.getText(),pro_na_tex.getText(),quan_tex.getText(),combe_size.getSelectedItem(),pri_tex.getText()});
            //cost=Double.parseDouble(cost1);
            id_tex.setText("");
            pro_na_tex.setText("");
            quan_tex.setText("");
            pri_tex.setText("");
        }
     
        
        
        
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_add_but1ActionPerformed

    private void delete_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_butActionPerformed

    DefaultTableModel model = (DefaultTableModel) table1.getModel();  
    
    model.removeRow(table1.getSelectedRow());
        id_tex.setText(""); 
        pro_na_tex.setText("");
        quan_tex.setText("");
        pri_tex.setText("");

// TODO add your handling code here:
    }//GEN-LAST:event_delete_butActionPerformed

    private void update_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_butActionPerformed

         DefaultTableModel model = (DefaultTableModel) table1.getModel();  
           
         model.setValueAt(id_tex.getText(), table1.getSelectedRow(), 0);
         model.setValueAt(pro_na_tex.getText(), table1.getSelectedRow(), 1);
         model.setValueAt(quan_tex.getText(), table1.getSelectedRow(), 2);
         model.setValueAt(combe_size.getSelectedItem(), table1.getSelectedRow(), 3);
         model.setValueAt(pri_tex.getText(), table1.getSelectedRow(), 4);
        
        id_tex.setText(""); 
        pro_na_tex.setText("");
        quan_tex.setText("");
        pri_tex.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_update_butActionPerformed

    private void cost_texActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cost_texActionPerformed

//        DefaultTableModel model = (DefaultTableModel) table1.getModel();  
  

// TODO add your handling code here:
    }//GEN-LAST:event_cost_texActionPerformed

    private void id_texActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_texActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_texActionPerformed

    private void total_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_butActionPerformed
        

DefaultTableModel model = (DefaultTableModel) table1.getModel(); 
   double s=0;//sum of price

for(int i=0;i<table1.getRowCount();i++){
    String d= model.getValueAt(i, 4).toString();
    double d1=Double.parseDouble(d);
    s+=d1;
}
        
String tot = Double.toString(s);
        cost_tex.setText(tot);

// TODO add your handling code here:
    }//GEN-LAST:event_total_butActionPerformed

    private void jScrollPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseClicked

         

// TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane3MouseClicked

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
 DefaultTableModel model = (DefaultTableModel) table1.getModel();  
           
       id_tex.setText(model.getValueAt(table1.getSelectedRow(), 0).toString());
       pro_na_tex.setText(model.getValueAt(table1.getSelectedRow(), 1).toString());  
        quan_tex.setText(model.getValueAt(table1.getSelectedRow(),2).toString()); 
      combe_size.setSelectedItem(model.getValueAt(table1.getSelectedRow(),3).toString()); 
       pri_tex.setText(model.getValueAt(table1.getSelectedRow(),4).toString()); 
// TODO add your handling code here:
    }//GEN-LAST:event_table1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_su.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_su.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_su.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_su.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
     
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_su().setVisible(true);
            }
        });
    
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_but1;
    private javax.swing.JComboBox combe_size;
    private javax.swing.JTextField cost_tex;
    private javax.swing.JButton delete_but;
    private javax.swing.JTextField id_tex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField pri_tex;
    private javax.swing.JTextField pro_na_tex;
    private javax.swing.JTextField quan_tex;
    private javax.swing.JTable table1;
    private javax.swing.JButton total_but;
    private javax.swing.JButton update_but;
    // End of variables declaration//GEN-END:variables
}
